# version: '2.1'

# services:
#   btms-web:
#     image: btms-web:dev
#     build: .
#     environment:
#       NODE_ENV: dev
#     ports:
#       - 8100:80
# networks:
#   default:
#     external:
#       name: nginx-proxy-docker

version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8100:80